# Generated by Django 5.1.7 on 2025-03-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_rename_message_thread_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-update']},
        ),
        migrations.AddField(
            model_name='thread',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
